development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: fat_wallet_rails_dev
  pool: 5
  username: root
  password: paul123
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: fat_wallet_rails_test
  pool: 5
  username: root
  password: paul123
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: fat_wallet_rails
  pool: 5
  username: root
  password: paul123
